<?php

namespace AppBundle\Repository;

/**
 * UserProductsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserProductsRepository extends \Doctrine\ORM\EntityRepository
{
}
